import Head from "next/head";
import { Container, MainWrapper, PageWrapper } from "@/components";
import {
    HomePageCategories,
    HomePageCheckbox,
    HomePageInfo,
} from "@/pages/HomePage";

export default function Home() {
    return (
        <>
            <Head>
                <title>Главная</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageWrapper>
                <MainWrapper>
                    <Container>
                        <HomePageInfo />
                        <HomePageCategories />
                        <HomePageCheckbox />
                    </Container>
                </MainWrapper>
            </PageWrapper>
        </>
    );
}
